// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	translator "github.com/ksysoev/gotext-translator/pkg/translator"
	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// CreateTranslator provides a mock function with given fields: config
func (_m *Provider) CreateTranslator(config map[string]interface{}) (translator.Translator, error) {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for CreateTranslator")
	}

	var r0 translator.Translator
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) (translator.Translator, error)); ok {
		return rf(config)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) translator.Translator); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(translator.Translator)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetName provides a mock function with no fields
func (_m *Provider) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
