// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Translator is an autogenerated mock type for the Translator type
type Translator struct {
	mock.Mock
}

// Translate provides a mock function with given fields: ctx, text, targetLang
func (_m *Translator) Translate(ctx context.Context, text string, targetLang string) (string, error) {
	ret := _m.Called(ctx, text, targetLang)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, text, targetLang)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, text, targetLang)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, text, targetLang)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTranslator creates a new instance of Translator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Translator {
	mock := &Translator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
