# OpenAI Configuration
llm:
  provider: openai
  api_key: sk-your-openai-api-key
  model: gpt-3.5-turbo  # or gpt-4, etc.

# Anthropic Configuration
# llm:
#   provider: anthropic
#   api_key: sk-ant-your-anthropic-api-key
#   model: claude-3-haiku  # or claude-3-opus, claude-3-sonnet, etc.
