# OpenAI Configuration
llm:
  provider: openai
  api_key: sk-your-openai-api-key
  model: gpt-3.5-turbo  # or gpt-4, etc.

# OpenRouter Configuration
# llm:
#   provider: openrouter
#   api_key: your-openrouter-api-key
#   model: openai/gpt-3.5-turbo  # or anthropic/claude-3-opus, mistralai/mistral-tiny, etc.
#   options:
#     route_prefix: gotext-translator